language: java
env:
  - MAVEN_VERSION=3.0.5
  - MAVEN_VERSION=3.1.1
  - MAVEN_VERSION=3.2.5
  - MAVEN_VERSION=3.3.1
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.0
  - MAVEN_VERSION=3.5.2
  - MAVEN_VERSION=3.5.3
  - MAVEN_VERSION=3.5.4

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION} -Dhttps.protocols=TLSv1.2"

script:
  - "./mvnw --show-version --errors --batch-mode -Prun-its clean verify -Dhttps.protocols=TLSv1.2"
jdk:
 - openjdk10
 - openjdk9
 - openjdk8

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
